language: cpp
dist: xenial
sudo: required
env:
  - COMPILER=gcc-6 CCOMPILER=g++-6 BOOST_VER=1.69.0
  - COMPILER=gcc-7 CCOMPILER=g++-7 BOOST_VER=1.69.0
  - COMPILER=clang-6.0 CCOMPILER=clang++-6.0 BOOST_VER=1.69.0
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/trusty/ llvm-toolchain-xenial-6 main" | sudo tee -a /etc/apt/sources.list && echo "deb-src http://apt.llvm.org/trusty/ llvm-toolchain-xenial-7 main" | sudo tee -a /etc/apt/sources.list
  - cat /etc/apt/sources.list && sudo apt-get update -q
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y gcc-6 g++-6 gcc-7 g++-7 clang-6.0
  - sudo pip install -U pip && pip install --user cpp-coveralls cpplint
install:
  - export BOOST_VERSION=${BOOST_VER//./_} && export BOOST_ROOT=${HOME}/${CCOMPILER}-boost_${BOOST_VER//./_}
  - travis_wait ./install-boost.sh
script:
  - export CC=$COMPILER && export CXX=$CCOMPILER && mkdir build && cd build && cmake .. && make -j8 2>&1 > /dev/null && make test ARGS="-VV" && cd ..
  - (cpplint --output=emacs --recursive --counting=detailed  ./algo ./clrs ./effective-modern-cpp ./cppp 2>&1 | grep -v "Done" | grep -v "Ignoring") || echo "0"
cache:
  directories:
    - "${HOME}/${CCOMPILER}-boost_${BOOST_VER//./_}"
notifications:
  slack:
    secure: jJM62Z4tppIg7qSdnXO1X0fWfWmZBRfKififFUew+CXyy/LI/cPOhC+zxCbH5kF9jXJhCc6SltYIO29rTnciBOF6nIMjL4ZY/n9xJsR/RQylOq9nxDrqPgKoN4lExuDqAvFq8ZM/+4GKKOlbSXm5IBDlT2HvNae6+Nv8lx22Vzm1SPNmy40PGsfEpd41/sFJQRMPGCjT6y2iXYya2uPYB8xW73uHn36X4SO0tIswn1R/H36qU1znRpAQCzAbeFaaaBf4o8WsbY7fKs4lPSUZZT5Z9O0TY0M7qpSwLDWsCOcwuheGaYnzdTLti2cb0aLuF7LEEt37m0k+QjVz+UjKeEkTKKcvF/GOen5RjG/Ti4OlAfD/mHUHXtBW4x5cHo74upFuBKz229jqZ+QYGFiyeajikdQ4xRsviRpUXENmAEDRdmmcOcFuXKQcUgiL7F6mExfIQMkrPjnVPtN1ZlOb+I4ikZoK6IitWRq5HvR2e8gUMs1uKHq1ZBf+0RIb72ZKnI74DKiA7bKARMrlciZz3Yjxd55oNP5di1cSPFd5YrJSLGW2ckxJVy1A4wF1RmtmwWjLTUtPEFZHGIZ+mOhNk0nj8V9s24hsGYCe1cu0y/NdT6gZSwYX7bd6KLO/7qM9S8QGGmxcwpW2+i3QAnOHXsGiiMYV0CZ9FTwfQxIcfYU=
