language: cpp
addons:
    apt:
      sources:
        - ubuntu-toolchain-r-test
        - llvm-toolchain-precise-3.7
      packages:
        - gcc-4.9
        - g++-4.9
        - clang-3.7

os:
  - linux
  - osx
  - windows
        
compiler:
  - clang
  - gcc

before_script:
  - cmake .
  - make

  
  
  
