language: cpp
dist: focal
virt: vm
sudo: required

env:
  - COMPILER=gcc-9 CCOMPILER=g++-9 BOOST_VER=1.74.0
  - COMPILER=clang-10 CCOMPILER=clang++-10 BOOST_VER=1.74.0
before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - wget -O - http://llvm.org/apt/llvm-snapshot.gpg.key | sudo apt-key add -
  - echo "deb http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main" | sudo tee -a /etc/apt/sources.list && echo "deb-src http://apt.llvm.org/focal/ llvm-toolchain-focal-10 main" | sudo tee -a /etc/apt/sources.list
  - cat /etc/apt/sources.list && sudo apt-get update -q
  - sudo apt-get -o Dpkg::Options::="--force-overwrite" install -y clang-10
  - sudo apt remove --purge --auto-remove cmake
  - sudo pip install -U pip && pip install --user cpp-coveralls cpplint cmake conan
script:
  - export CC=$COMPILER && export CXX=$CCOMPILER
  - conan profile new default --detect
  - conan profile update settings.compiler.libcxx=libstdc++11 default
  - mkdir build && cd build && conan install .. --build missing && cmake .. && make -j8 2>&1 > /dev/null && make test ARGS="-VV" && cd ..
  - (cpplint --output=emacs --recursive --counting=detailed  ./algo ./clrs ./effective-modern-cpp ./cppp 2>&1 | grep -v "Done" | grep -v "Ignoring") || echo "0"
cache:
  directories:
    - $HOME/.conan/data
