version: 2.1

commands:
  build_test:
    parameters:
      tag:
        default: "base c++ image"
        type: string
    steps:
      - checkout
      - restore_cache:
         key: v1-{{ checksum "conanfile.txt" }}
      - run:
          name: deps
          command: |
            sudo apt-get update -q
            sudo pip install -U pip && pip install --user cpp-coveralls cpplint conan
      - run:
         name: conan, build, test and lint
         command: |
           conan profile new default --detect
           conan profile update settings.compiler.libcxx=libstdc++11 default
           mkdir build && cd build && conan install .. --build missing && cmake .. && make -j8 2>&1 > /dev/null && make test ARGS="-VV" && cd ..
           (cpplint --output=emacs --recursive --counting=detailed  ./algo ./clrs ./effective-modern-cpp ./cppp 2>&1 | grep -v "Done" | grep -v "Ignoring") || echo "0"
      - save_cache:
         key: v1-{{ checksum "conanfile.txt" }}
         paths:
           - $HOME/.conan/data

jobs:
  gcc:
    docker: 
      - image: "conanio/gcc11"
    steps:
      - build_test
  clang:
    docker:
      - image: "conanio/clang11"
    steps:
      - build_test

workflows:
  version: 2
  commit:
    jobs:
      - gcc
      - clang
