version: 2.1
build:
  docker:
    - image: << matrix.image >> 
  steps:
    - checkout
    - restore_cache:
        key: {{ image }}-{{ checksum "conanfile.txt" }}
    - run:
        name: deps
        command: |
          sudo apt-get update -q
          # sudo apt remove --purge --auto-remove cmake
          # sudo pip install -U pip && pip install --user cpp-coveralls cpplint cmake conan
          sudo pip install -U pip && pip install --user cpp-coveralls cpplint conan
    - run:
        name: conan, build, test and lint
        command: |
          conan profile new default --detect
          conan profile update settings.compiler.libcxx=libstdc++11 default
          mkdir build && cd build && conan install .. --build missing && cmake .. && make -j8 2>&1 > /dev/null && make test ARGS="-VV" && cd ..
          (cpplint --output=emacs --recursive --counting=detailed  ./algo ./clrs ./effective-modern-cpp ./cppp 2>&1 | grep -v "Done" | grep -v "Ignoring") || echo "0"
    - save_cache:
        key: {{ image }}-{{ checksum "conanfile.txt" }}
        paths:
          - $HOME/.conan/data

workflows:
  version: 2
  build_and_test:
    jobs:
      - build:
          matrix:
            parameters:
              # TODO: bump to 11 when stable
              image: ["conanio/gcc10", "conanio/clang11"]
