version: 2.1

commands:
  build_test:
    parameters:
      tag:
        default: "base c++ image"
        type: string
    steps:
      - checkout
      - restore_cache:
         key: v2-{{ checksum "conanfile.txt" }}-{{ .Environment.CIRCLE_JOB }}
      - run:
          name: deps
          command: |
            sudo apt-get update -q
            sudo pip install -U pip && pip install --user cpp-coveralls cpplint conan
      - run:
         name: conan, build, test and lint
         command: |
           conan profile new default --detect || echo "read conan profile from cache"
           conan profile update settings.compiler.libcxx=libstdc++11 default
           mkdir build && cd build && conan install .. --build missing && cmake ..
           find /home/conan/.conan/data/gtest/1.12.1 -type f -exec sed -i 's/__cpp_char8_t/__cpp_lib_char8_t/g' {} \;
           make -j8 2>&1 > /dev/null && make test ARGS="-VV" && cd ..
           (/home/conan/.local/bin/cpplint --output=emacs --recursive --counting=detailed  ./algo ./clrs ./effective-modern-cpp ./cppp 2>&1 | grep -v "Done" | grep -v "Ignoring") || echo "0"
      - save_cache:
         key: v2-{{ checksum "conanfile.txt" }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum ".circleci/config.yml" }}
         paths:
           - ~/.conan

jobs:
  gcc11:
    docker:
      - image: "conanio/gcc11"
    steps:
      - build_test
  clang14:
    docker:
      - image: "conanio/clang14-ubuntu18.04"
    steps:
      - build_test

workflows:
  version: 2
  commit:
    jobs:
      - gcc11
      - clang14
