#include <iostream>
#include "gtest/gtest.h"

// lambda expression: the source code
// clojure: runtime object generated by lambda,
// it holds copies/refs to captured data depend on mode.
// clojure class: a class from which clojure is instantiated

void copy() {
  int x = 2; // local
  auto c1 = [x](int y) {return x * y > 42;};
  auto c2 = c1; // copy of c1
  auto c3 = c2; // copy of c2
  std::cout << &c3 << std::endl;
}


TEST(AvoidDefaultCaptureTest, SomeTest) {
  EXPECT_EQ(1, 1);
}

int main(int argc, char *argv[]) {
  ::testing::InitGoogleTest(&argc, argv);
  int ret = RUN_ALL_TESTS();
  return ret;
}
