#include "gtest/gtest.h"

// lambda expression: the source code
// clojure: runtime object generated by lambda,
// it holds copies/refs to captured data depend on mode.
// clojure class: a class from which clojure is instantiated


TEST(AvoidDefaultCaptureTest, SomeTest) {
  EXPECT_EQ(1, 1);
}

int main(int argc, char *argv[]) {
  ::testing::InitGoogleTest(&argc, argv);
  int ret = RUN_ALL_TESTS();
  return ret;
}
